module.exports = require('yargs')
    .usage('Usage: $0 [Options]')
    .alias('u', 'url')
    .describe('u', 'Application URL')
    // .default('u', 'http://127.0.0.1:8000')
    .default('u', 'http://shtnr.me')
    .alias('p', 'port')
    .describe('p', 'Port number for the express application')
    .default('p', 8000)
    .describe('redis-host', 'Redis server hostname')
    .default('redis-host', 'localhost')
    .describe('redis-port', 'Redis server port number')
    .default('redis-port', '6379')
    .describe('redis-pass', 'Redis server password')
    .default('redis-pass', false)
    .describe('redis-db', 'Redis DB Index')
    .default('redis-db', 0)
    .help('h')
    .alias('h', 'help')
    .argv;